enableGlobalCache: false
nodeLinker: pnp

packageExtensions:
  "jest@*":
    peerDependencies:
      "ts-node": "*"
    peerDependenciesMeta:
      "ts-node":
        optional: true

  "jest-cli@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true

  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "ts-node":
        optional: true
